# Generated by Django 6.0.6 on 2026-07-08 00:50

import core.utils.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('reference', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': 'Concurso',
                'verbose_name_plural': 'Concursos',
                'db_table': 'contest',
                'ordering': ['-reference', '-date'],
            },
        ),
        migrations.CreateModel(
            name='Number',
            fields=[
                ('value', models.SmallIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
            ],
            options={
                'verbose_name': 'Número',
                'verbose_name_plural': 'Números',
                'db_table': 'number',
                'ordering': ['value'],
            },
        ),
        migrations.CreateModel(
            name='BettorUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=15, unique=True, validators=[core.utils.validators.validate_username])),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('initial', models.PositiveIntegerField()),
                ('final', models.PositiveIntegerField()),
                ('mirror', models.BooleanField(default=True)),
                ('bettor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aposta',
                'verbose_name_plural': 'Apostas',
                'db_table': 'bet',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='BetContest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bet')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.contest')),
            ],
            options={
                'verbose_name': 'Concurso apostado',
                'verbose_name_plural': 'Concursos apostados',
                'db_table': 'bet_contest',
            },
        ),
        migrations.AddField(
            model_name='bet',
            name='contests',
            field=models.ManyToManyField(related_name='bets', through='core.BetContest', to='core.contest'),
        ),
        migrations.CreateModel(
            name='ContestPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0, validators=[core.utils.validators.validate_range_points])),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('winners', models.PositiveIntegerField(default=0)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='core.contest')),
            ],
            options={
                'verbose_name': 'Prêmio de concurso',
                'verbose_name_plural': 'Prêmios de concursos',
                'db_table': 'contest_prize',
            },
        ),
        migrations.CreateModel(
            name='ContestNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contest')),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.number')),
            ],
            options={
                'verbose_name': 'Número de concurso',
                'verbose_name_plural': 'Números de concursos',
                'db_table': 'contest_number',
            },
        ),
        migrations.AddField(
            model_name='contest',
            name='numbers',
            field=models.ManyToManyField(related_name='contests', through='core.ContestNumber', to='core.number'),
        ),
        migrations.CreateModel(
            name='BetNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bet')),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.number')),
            ],
            options={
                'verbose_name': 'Número de aposta',
                'verbose_name_plural': 'Números de apostas',
                'db_table': 'bet_number',
            },
        ),
        migrations.AddField(
            model_name='bet',
            name='numbers',
            field=models.ManyToManyField(related_name='bets', through='core.BetNumber', to='core.number'),
        ),
        migrations.CreateModel(
            name='BetResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hits', models.PositiveIntegerField()),
                ('mirror_hits', models.PositiveIntegerField()),
                ('bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.bet')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bet_results', to='core.contest')),
            ],
            options={
                'verbose_name': 'Resultado da aposta',
                'verbose_name_plural': 'Resultados das apostas',
                'db_table': 'bet_result',
                'constraints': [models.UniqueConstraint(fields=('contest', 'bet'), name='unique_result_contest_bet')],
            },
        ),
        migrations.CreateModel(
            name='BetPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0, validators=[core.utils.validators.validate_range_points])),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='core.bet')),
                ('contest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bets_prizes', to='core.contest')),
            ],
            options={
                'verbose_name': 'Prêmio de Aposta',
                'verbose_name_plural': 'Prêmios de Apostas',
                'db_table': 'bet_prize',
                'ordering': ['-bet__date', '-points'],
                'constraints': [models.UniqueConstraint(fields=('bet', 'contest', 'points'), name='unique_bet_prize_contest_points')],
            },
        ),
        migrations.AddConstraint(
            model_name='betcontest',
            constraint=models.UniqueConstraint(fields=('contest', 'bet'), name='unique_contest_bet'),
        ),
        migrations.AddConstraint(
            model_name='contestnumber',
            constraint=models.UniqueConstraint(fields=('number', 'contest'), name='unique_number_contest'),
        ),
        migrations.AddConstraint(
            model_name='betnumber',
            constraint=models.UniqueConstraint(fields=('number', 'bet'), name='unique_number_bet'),
        ),
    ]
